/**
 * account
 */
export const LOGIN = 'LOGIN'
export const LOGOUT = 'LOGOUT'

/**
 * studentData
 */
export const SET_STUDENT_DATA = 'SET_STUDENT_DATA'
export const SET_CURRENT_TRACK = 'SET_CURRENT_TRACK'
export const SET_CURRENT_TOPIC = 'SET_CURRENT_TOPIC'
export const SET_SUGGESTED_ACTIVITY = 'SET_SUGGESTED_ACTIVITY'
// export const SET_CURRENT_TOPIC_MODULES = "SET_CURRENT_TOPIC_MODULES";

/**
 * learnData
 */
export const SET_CURRENT_CARD_BY_INDEX = 'SET_CURRENT_CARD_BY_INDEX'
export const INCREMENT_CURRENT_CARD_INDEX = 'INCREMENT_CURRENT_CARD_INDEX'

export const SET_LAST_CARD_COMPLETED_INDEX_BY_ID =
	'SET_LAST_CARD_COMPLETED_INDEX_BY_ID'
export const INCREMENT_LAST_CARD_COMPLETED_INDEX =
	'INCREMENT_LAST_CARD_COMPLETED_INDEX'

export const SET_ALL_CARDS = 'SET_ALL_CARDS'
export const SET_ACTIVITY = 'SET_ACTIVITY' // contentful

/**
 * viewManager
 */
export const SET_VIEW_STUDENT = 'SET_VIEW_STUDENT'

/**
 * Theme
 */
export const SET_THEME = 'SET_THEME'
