export const LOGIN = "LOGIN";
export const LOGOUT = "LOGOUT";

export const SET_STUDENT_DATA = "SET_STUDENT_DATA";
export const SET_CURRENT_TRACK = "SET_CURRENT_TRACK";
export const SET_CURRENT_TOPIC = "SET_CURRENT_TOPIC";
export const SET_SUGGESTED_ACTIVITY = "SET_SUGGESTED_ACTIVITY";
// export const SET_CURRENT_TOPIC_MODULES = "SET_CURRENT_TOPIC_MODULES";

export const SET_VIEW_STUDENT = "SET_VIEW_STUDENT";

export const SET_THEME = "SET_THEME"
